# Generated by Django 4.2.7 on 2023-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_add', models.DateField()),
                ('Uid', models.TextField()),
                ('Temp', models.FloatField()),
                ('Humidity', models.FloatField()),
            ],
        ),
    ]
